name: "Run Bruno Checkout On Push"

on:
  push:

env:
  verifier_email: ${{ vars.VERIFIER_CONTACT_EMAIL }}
  vault_ur_base: https://vault-uat.us.equifax.com
  vault_username: ${{ secrets.VAULT_USERNAME }}
  vault_password: ${{ secrets.VAULT_PASSWORD }}
  ENV: ${{ vars.ENVIRONMENT_STAGE }}

jobs:
  run-bruno:
    runs-on: ubuntu-latest
    environment: 'QA'
    steps:
    - name: print all stuff
      run: |
        echo "environment_stage: ${{ vars.ENVIRONMENT_STAGE }}"
        echo "ENV: ${ENV}"
        echo "environment upper: ${ENV^^}"
        echo "email: ${{ vars.VERIFIER_CONTACT_EMAIL }}"
        echo "vault-user: ${vault_username}"
        echo "vault-password: ${vault_password}"
